"""
Design a program to take a word as an input, and then encode it into a Pig Latin.
A Pig Latin is an encrypted word in English, which is generated by the first vowel occurring
in the input word is placed at the start of the new word along with the remaining alphabets of it.
The alphabets present before the first vowel are shifted at the end of the new word followed by “ay”.
"""

